# -*- coding: utf-8 -*-
"""email_summarizer_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-WA068Vm49WpPBpa1n4pbIeqLXTTt8z5
"""

#!pip install -q \
#transformers==4.52.4 \
#torch \
#sentencepiece \
#spacy \
#datasets \
#accelerate

#!python -m spacy download en_core_web_sm

import re
import torch
import spacy

from transformers import pipeline

print("Transformers version:")
import transformers
print(transformers.__version__)

from transformers.pipelines import SUPPORTED_TASKS

print("summarization" in SUPPORTED_TASKS)

print("Loading summarizer...")
summarizer = pipeline(
    "summarization",
    model="facebook/bart-large-cnn",
    device=0 if torch.cuda.is_available() else -1
)

print("Loading intent classifier...")
intent_classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli",
    device=0 if torch.cuda.is_available() else -1
)

print("Loading spaCy NER...")
nlp = spacy.load("en_core_web_sm")

print("All models loaded.")

#Preprocessor
def preprocess_email(raw_text: str) -> str:
    """
    Cleans raw email text before passing to models.
    - Strips quoted reply chains (lines starting with >)
    - Removes excessive whitespace
    - Strips common email headers if present
    """
    # Remove quoted reply lines
    lines = raw_text.splitlines()
    cleaned = [l for l in lines if not l.strip().startswith(">")]

    # Remove lines that look like forwarded headers
    header_patterns = re.compile(
        r"^(From:|To:|Cc:|Bcc:|Date:|Subject:|Sent:|On .+ wrote:)",
        re.IGNORECASE
    )
    cleaned = [l for l in cleaned if not header_patterns.match(l.strip())]

    text = " ".join(cleaned)

    # Collapse whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text


def chunk_text(text: str, max_tokens: int = 900) -> list[str]:
    """
    BART has a 1024-token limit. Split long emails into
    overlapping chunks so nothing important gets cut off.
    Splits on sentence boundaries where possible.
    """
    sentences = re.split(r"(?<=[.!?])\s+", text)
    chunks, current = [], ""

    for sentence in sentences:
        # Rough token estimate: 1 token ≈ 4 characters
        if len(current) + len(sentence) > max_tokens * 4:
            if current:
                chunks.append(current.strip())
            current = sentence
        else:
            current += " " + sentence

    if current.strip():
        chunks.append(current.strip())

    return chunks if chunks else [text]

#summarizer
def summarize_email(text: str) -> str:
    """
    Runs extractive → abstractive summarization.
    For multi-chunk emails, summarizes each chunk then
    summarizes the combined result (two-pass).
    """
    chunks = chunk_text(text)

    chunk_summaries = []
    for chunk in chunks:
        if len(chunk.split()) < 30:
            # Too short to summarize, use as-is
            chunk_summaries.append(chunk)
            continue

        result = summarizer(
            chunk,
            max_length=130,
            min_length=30,
            do_sample=False
        )
        chunk_summaries.append(result[0]["summary_text"])

    # If multiple chunks, do a second-pass summary
    if len(chunk_summaries) > 1:
        combined = " ".join(chunk_summaries)
        final = summarizer(
            combined,
            max_length=150,
            min_length=40,
            do_sample=False
        )
        return final[0]["summary_text"]

    return chunk_summaries[0]

#NER extractor
def extract_entities(text: str) -> dict:
    """
    Uses spaCy to extract named entities from the email.
    Returns grouped by entity type.
    """
    doc = nlp(text)

    entities = {
        "people":        [],
        "organizations": [],
        "dates":         [],
        "locations":     [],
        "money":         [],
        "misc":          [],
    }

    label_map = {
        "PERSON":   "people",
        "ORG":      "organizations",
        "DATE":     "dates",
        "TIME":     "dates",
        "GPE":      "locations",
        "LOC":      "locations",
        "MONEY":    "money",
        "PRODUCT":  "misc",
        "EVENT":    "misc",
        "WORK_OF_ART": "misc",
    }

    for ent in doc.ents:
        key = label_map.get(ent.label_)
        if key and ent.text not in entities[key]:
            entities[key].append(ent.text)

    # Remove empty keys
    return {k: v for k, v in entities.items() if v}

#Action item detector
ACTION_VERBS = re.compile(
    r"\b(please|kindly|could you|can you|would you|need you to|"
    r"make sure|ensure|don't forget|remember to|review|send|"
    r"confirm|schedule|call|follow up|update|approve|check|reply)\b",
    re.IGNORECASE
)

def extract_action_items(text: str) -> list[str]:
    """
    Heuristic extraction of sentences that look like action items.
    Looks for imperative or request-style sentences.
    """
    sentences = re.split(r"(?<=[.!?])\s+", text)
    actions = []

    for s in sentences:
        s = s.strip()
        if ACTION_VERBS.search(s) and len(s) > 15:
            actions.append(s)

    return actions[:5]  # Cap at 5 to keep it useful

# Intent classifier
INTENT_LABELS = [
    "urgent action required",
    "needs a reply",
    "for your information only",
    "meeting or scheduling request",
    "follow-up reminder",
    "newsletter or promotional",
]

def classify_intent(text: str) -> dict:
    """
    Zero-shot classification to detect email intent.
    Uses the summary (not full text) for speed.
    Returns top intent + confidence score.
    """
    # Use first 512 chars for speed — the summary is ideal here
    snippet = text[:512]

    result = intent_classifier(
        snippet,
        candidate_labels=INTENT_LABELS,
        hypothesis_template="This email is {}."
    )

    # Return top 2 intents with scores
    top_intents = [
        {"label": label, "score": round(score, 3)}
        for label, score in zip(result["labels"][:2], result["scores"][:2])
    ]

    return {
        "primary": top_intents[0]["label"],
        "confidence": top_intents[0]["score"],
        "secondary": top_intents[1] if len(top_intents) > 1 else None,
    }

#Priority scorer
URGENT_WORDS = re.compile(
    r"\b(urgent|asap|immediately|critical|deadline|overdue|"
    r"as soon as possible|time.sensitive|emergency|by end of day|"
    r"by tomorrow|today|tonight)\b",
    re.IGNORECASE
)

def score_priority(text: str, intent: dict) -> str:
    """
    Combines keyword heuristics + intent classification
    to assign a simple priority: High / Medium / Low
    """
    urgent_hits = len(URGENT_WORDS.findall(text))

    if urgent_hits >= 2 or "urgent" in intent["primary"]:
        return "High"
    elif intent["primary"] in ("needs a reply", "meeting or scheduling request"):
        return "Medium"
    elif "newsletter" in intent["primary"] or intent["confidence"] < 0.4:
        return "Low"
    else:
        return "Medium"

#Master pipeline
def run_pipeline(raw_email: str) -> dict:
    """
    Full pipeline: takes raw email text, returns structured output.

    Returns:
    {
        "summary":      str,
        "intent":       { primary, confidence, secondary },
        "priority":     "High" | "Medium" | "Low",
        "entities":     { people, organizations, dates, ... },
        "action_items": [ str, ... ],
        "word_count":   { original, summary }
    }
    """
    # Step 1 — clean
    clean = preprocess_email(raw_email)

    # Step 2 — summarize
    print("  Summarizing...")
    summary = summarize_email(clean)

    # Step 3 — NER on clean text
    print("  Extracting entities...")
    entities = extract_entities(clean)

    # Step 4 — action items
    action_items = extract_action_items(clean)

    # Step 5 — intent on summary (faster + more focused)
    print("  Classifying intent...")
    intent = classify_intent(summary)

    # Step 6 — priority
    priority = score_priority(clean, intent)

    return {
        "summary":      summary,
        "intent":       intent,
        "priority":     priority,
        "entities":     entities,
        "action_items": action_items,
        "word_count": {
            "original": len(clean.split()),
            "summary":  len(summary.split()),
        }
    }

#Test
SAMPLE_EMAIL = """
Hi Sarah,

Hope you're doing well. I wanted to follow up on the Q3 budget report
we discussed last Tuesday. The finance team at Anthropic needs the final
numbers by Friday, October 20th — this is urgent as the board meeting
is scheduled for Monday the 23rd.

Could you please send over the revised projections for the APAC region?
Also, make sure to include the headcount changes from the Singapore office.
John from Legal mentioned he needs a copy as well for the compliance review.

Let me know if you have any questions. We can schedule a quick call
Thursday afternoon if needed.

Best,
Michael
"""

print("Running pipeline on sample email...\n")
result = run_pipeline(SAMPLE_EMAIL)

print("\n── RESULTS ──────────────────────────────────────────")
print(f"Priority:   {result['priority']}")
print(f"Intent:     {result['intent']['primary']} ({result['intent']['confidence']:.0%})")
print(f"Summary:    {result['summary']}")
print(f"Entities:   {result['entities']}")
print(f"Actions:    {result['action_items']}")
print(f"Words:      {result['word_count']['original']} → {result['word_count']['summary']}")

