# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W4rCaltC_a0hO1mpldpCwSCTAmecPdAG
"""

#!pip install fastapi uvicorn pyngrok nest-asyncio transformers==4.52.4 torch sentencepiece spacy datasets accelerate
#!python -m spacy download en_core_web_sm

#!pip install fastapi uvicorn pyngrok nest-asyncio

#from google.colab import files
#files.upload()

import os

for f in os.listdir():
    print(f)

with open("email_summarizer_pipeline.py") as f:
    text = f.read()

print("def run_pipeline" in text)

import sqlite3
import hashlib
import json
import time
import threading
import uvicorn
import nest_asyncio
from datetime import datetime
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from pyngrok import ngrok
from email_summarizer_pipeline import run_pipeline

#Database setup
DB_PATH = "summaries.db"

def init_db():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("""
        CREATE TABLE IF NOT EXISTS summaries (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            email_hash  TEXT UNIQUE,
            raw_preview TEXT,
            result_json TEXT,
            created_at  TEXT
        )
    """)
    c.execute("""
        CREATE TABLE IF NOT EXISTS request_log (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            email_hash  TEXT,
            cache_hit   INTEGER,
            duration_ms INTEGER,
            created_at  TEXT
        )
    """)
    conn.commit()
    conn.close()
    print("Database ready.")

init_db()


def get_cached(email_hash: str):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute(
        "SELECT result_json FROM summaries WHERE email_hash = ?",
        (email_hash,)
    )
    row = c.fetchone()
    conn.close()
    return json.loads(row[0]) if row else None


def save_to_cache(email_hash: str, raw_preview: str, result: dict):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute(
        """INSERT OR REPLACE INTO summaries
           (email_hash, raw_preview, result_json, created_at)
           VALUES (?, ?, ?, ?)""",
        (email_hash, raw_preview[:200], json.dumps(result),
         datetime.utcnow().isoformat())
    )
    conn.commit()
    conn.close()


def log_request(email_hash: str, cache_hit: bool, duration_ms: int):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute(
        """INSERT INTO request_log
           (email_hash, cache_hit, duration_ms, created_at)
           VALUES (?, ?, ?, ?)""",
        (email_hash, int(cache_hit), duration_ms,
         datetime.utcnow().isoformat())
    )
    conn.commit()
    conn.close()

#FastAPI app
app = FastAPI(title="Email Summarizer API", version="1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],       # Chrome extension can call from any origin
    allow_methods=["*"],
    allow_headers=["*"],
)

# Request / Response schemas
class SummarizeRequest(BaseModel):
    email_body: str
    force_refresh: bool = False   # set True to bypass cache


class SummarizeResponse(BaseModel):
    summary:      str
    intent:       dict
    priority:     str
    entities:     dict
    action_items: list
    word_count:   dict
    cache_hit:    bool
    duration_ms:  int

#Routes
@app.get("/")
def health_check():
    return {"status": "ok", "message": "Email Summarizer API is running"}


@app.post("/summarize", response_model=SummarizeResponse)
def summarize(req: SummarizeRequest):
    if not req.email_body or len(req.email_body.strip()) < 20:
        raise HTTPException(
            status_code=400,
            detail="Email body is too short or empty."
        )

    # Hash the email to use as a cache key
    email_hash = hashlib.sha256(
        req.email_body.strip().encode()
    ).hexdigest()

    start = time.time()

    # Check cache first
    if not req.force_refresh:
        cached = get_cached(email_hash)
        if cached:
            duration = int((time.time() - start) * 1000)
            log_request(email_hash, cache_hit=True, duration_ms=duration)
            return SummarizeResponse(
                **cached,
                cache_hit=True,
                duration_ms=duration
            )

    # Run the NLP pipeline
    try:
        result = run_pipeline(req.email_body)
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Pipeline error: {str(e)}"
        )

    duration = int((time.time() - start) * 1000)

    # Save to cache
    save_to_cache(email_hash, req.email_body, result)
    log_request(email_hash, cache_hit=False, duration_ms=duration)

    return SummarizeResponse(
        **result,
        cache_hit=False,
        duration_ms=duration
    )


@app.get("/history")
def get_history(limit: int = 20):
    """Returns recent summaries from the cache."""
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute(
        """SELECT email_hash, raw_preview, result_json, created_at
           FROM summaries
           ORDER BY created_at DESC
           LIMIT ?""",
        (limit,)
    )
    rows = c.fetchall()
    conn.close()

    return [
        {
            "id":         row[0][:8],   # short hash preview
            "preview":    row[1],
            "result":     json.loads(row[2]),
            "created_at": row[3],
        }
        for row in rows
    ]


@app.delete("/history")
def clear_history():
    """Clears all cached summaries."""
    conn = sqlite3.connect(DB_PATH)
    conn.execute("DELETE FROM summaries")
    conn.execute("DELETE FROM request_log")
    conn.commit()
    conn.close()
    return {"message": "Cache cleared."}

import os
import threading
import nest_asyncio
import uvicorn
from pyngrok import ngrok

# start server with ngrok
def start_server():
    nest_asyncio.apply()

    try:
        # Retrieve the token securely from the system environment variables
        NGROK_TOKEN = os.environ.get('NGROK_AUTHTOKEN')

        if not NGROK_TOKEN:
            print("❌ Error: 'NGROK_TOKEN' environment variable is missing.")
            print("Please make sure you are passing it from your host notebook cell.")
            return

        ngrok.set_auth_token(NGROK_TOKEN)
    except Exception as e:
        print(f"❌ Error setting ngrok token: {e}")
        return

    # Open ngrok tunnel on port 8000
    try:
        tunnel = ngrok.connect(8000)
        public_url = tunnel.public_url
    except Exception as e:
        print(f"❌ Error connecting to ngrok: {e}")
        return

    print("\n" + "="*50)
    print(f"  Public API URL:  {public_url}")
    print(f"  Health check:    {public_url}/")
    print(f"  Summarize:       {public_url}/summarize")
    print(f"  History:         {public_url}/history")
    print("="*50)
    print("\n  Copy the URL above into extension/background.js\n")

    # Start the FastAPI application via uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)

# Run in a thread so Colab stays interactive
thread = threading.Thread(target=start_server, daemon=True)
thread.start()

